
spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:e3122928953516752200dd6346b870e53585fb28542d9b7ebeb04835586184f0}

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.healthapp.gateway: DEBUG
