spring:
  application:
    name: user-service
  
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/health_user_db}
      database: health_user_db
      auto-index-creation: true
  
  cloud:
    config:
      enabled: false

server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always

app:
  jwt:
    secret: ${JWT_SECRET:e3122928953516752200dd6346b870e53585fb28542d9b7ebeb04835586184f0}
    access-token-expiration: 900000
    issuer: health-app

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.healthapp.user: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}