spring:
  application:
    name: discovery-service

server:
  port: 8787

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
