# Configuration du Discovery Service (Eureka Server)
spring:
  application:
    name: discovery-service

# Port du serveur Eureka
server:
  port: 8761

# Configuration Eureka
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  
  client:
    # Le serveur Eureka ne s'enregistre pas chez lui-même
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  
  server:
    # Désactive la protection contre les pannes réseau (pour le développement)
    enable-self-preservation: false
    # Intervalle de nettoyage des services inactifs
    eviction-interval-timer-in-ms: 3000

# Configuration du logging
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator endpoints pour le monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always